version: '2'
services:
  sso:
    image: 9178630400a9
    #container_name: blissful_tesla
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8443:8443
      - 8444:8444
      - 8888:8888
      - 8889:8889
      - 8081:8081
      - 8080:8080
      - 8083:8083

#  |Module Name| Module Introduction| Port Status| Must Be https|path|Start Sequencing |
#  |:----------|:-------------------|:-----------|:-------------|:---|:---|
#  |sso-server|cas|8443|√|cas|2|
#  |sso-config|Configuration Center|8888|×|config|1|
#  |sso-management|service management|8081|×|cas-management|3|
#  |sso-cas-client-demo|cas-client-demo|8080|×|/sample|4|
#  |sso-client-shiro-demo|shiro-client-demo|8083|×|/|5|
#  |sso-client-proxy-demo|OAuth2 proxy forwarding client|8808|×|/|6|
#  |sso-monitor|Monitoring Services|8444|×|/|7|