version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:3.6'
    container_name: china-sso-mongodb-3-6-primary
    ports:
      - "27017:27017"
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
#      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_USERNAME=cas-config
      - MONGODB_PASSWORD=123456
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_DATABASE=cas-mongo-database
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local