version: '2'
services:
  sso:
    image: china-sso-test-image:latest
    container_name: china-sso-test
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8443:8443 #  |sso-server|cas|8443|√|cas|2|
      - 8444:8444 #  |sso-monitor|Monitoring Services|8444|×|/|7|
      - 8888:8888 #  |sso-config|Configuration Center|8888|×|config|1|
      - 8889:8889 #  |sso-management|service management|8081|×|cas-management|3|
      - 8081:8081
      - 8808:8808 #  |sso-client-proxy-demo|OAuth2 proxy forwarding client|8808|×|/|6|
      - 8080:8080 #  |sso-cas-client-demo|cas-client-demo|8080|×|/sample|4|
      - 8083:8083 #  |sso-client-shiro-demo|shiro-client-demo|8083|×|/|5|
      #- 5000:5000 # debug, https://blog.csdn.net/u010475041/article/details/78623405
    depends_on:
      - mongodb
    extra_hosts:
      - "passport.sso.com:127.0.0.1"

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

  mongodb:
    image: 'bitnami/mongodb:3.6'
    container_name: china-sso-mongodb-3-6-primary
    ports:
      - "27017:27017"
    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
#      - MONGODB_SYSTEM_LOG_VERBOSITY=3
      - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
      - MONGODB_USERNAME=cas-config
      - MONGODB_PASSWORD=123456
      - MONGODB_ROOT_PASSWORD=123456
      - MONGODB_DATABASE=cas-mongo-database
    volumes:
      - 'mongodb_data:/bitnami'

volumes:
  mongodb_data:
    driver: local
  my-db:
    driver: local
