base:
  url: passport.sso.com
logging:
  file: "logs/sso-demo-proxy.log"
info:
  name: "Proxy login request"

server:
  port: 8808
spring:
  application:
    name: client-proxy
  profiles:
    active: dev
---
spring:
  profiles: dev
  boot:
    admin:
      # sso-monitor
      url: http://${base.url}:8444/
      client:
        # proxy-demo
        management-base-url: http://${base.url}:8808
        management-url: ${spring.boot.admin.client.management-base-url}
        service-url: ${spring.boot.admin.client.management-base-url}
        health-url: http://${base.url}:8808/health
management:
  security:
    enabled: false

security:
  basic:
    enabled: false