# The configuration file must be specified or the monitoring system cannot obtain
base:
  url: passport.sso.com
logging:
  file: "logs/monitor/monitor-server.log"
info:
  name: "surveillance system"
---
spring:
  application:
    name: sso-monitor
  profiles:
    active:
      # Enable security configuration
      - dev
# Current project port
server:
  port: 8444

---
spring:
  profiles: dev
  boot:
    admin:
      url: http://${base.url}:8444/
      client:
        management-base-url: ${spring.boot.admin.url}
        management-url: ${spring.boot.admin.url}
        service-url: ${spring.boot.admin.url}
management:
  security:
    enabled: false

security:
  basic:
    enabled: false