base:
  url: passport.sso.com
logging:
  file: "logs/config/sso-config.log"
info:
  name : "Configuration center"

server:
  port: 8888
  context-path: /config
spring:
  profiles:
    active:
      - native
      - dev
  application:
    name: sso-config


---
spring:
  profiles: dev
  boot:
    admin:
      # sso-monitor
      url: http://${base.url}:8444/
      client:
        management-base-url: http://${base.url}:${server.port}${server.context-path}
        management-url: ${spring.boot.admin.client.management-base-url}
        service-url: ${spring.boot.admin.client.management-base-url}
management:
  security:
    enabled: false

security:
  basic:
    enabled: false